# Generated by Django 4.0 on 2021-12-19 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base_part', '0002_alter_clothes_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 14, 34, 59, 904415, tzinfo=utc), verbose_name='date published'),
        ),
    ]
